### PR TITLE
Add API Client Library and Integrate VDYP Frontend with the Library

### PR DESCRIPTION
**Pull request by vividroyjeong**
- Add generated API Client Library into frontend via Swagger editor
- Rename default-api.ts -> vdyp-api.ts file and file-api -> vdyp-api client library folder for clarity
- Eliminate in-direct endpoint handling because of using the Client library
- Refactor API Integration to Utilize Generated API Client Library
- Fix an issue with model parameter panels appearing on the results tab screen('Model Report', 'View Log File', 'View Error Messages')
- Adjust the position of the 'Run Model' button card and input fields on the 'File Upload' screen

### CODE REVIEW

**Review by dhlevi — CHANGES_REQUESTED** [review]
I don't think the naming "Default-api" makes sense, so we'll want to change this to be more specific to "vdyp" unless we're expecting to have multiple clients that may require a default?

**Comment by vividroyjeong** [comment]
@dhlevi Thank you so much for the good suggestion, I will rename that file to vdyp-api. 

Also, I called the API folder 'file-api', in fact, I was thinking of changing it to 'projection-api' because it's not very clear, is that okay? I'm thinking of renaming it that way for extensibility because I thought there might be other API client libraries in the future. However, I am not sure about that. If no other client libraries are added, I guess we could just call it 'api' or 'vdyp-api'. Any advice would be appreciated.

> I don't think the naming "Default-api" makes sense, so we'll want to change this to be more specific to "vdyp" unless we're expecting to have multiple clients that may require a default?

**Comment by vividroyjeong** [comment]
@dhlevi after the code review, there were additional other changes as well as file name change. I've changed the comment at the top of this PR screen to include the changes, and I've also changed the PR title. Please review this PR again. Thanks!

**Review by dhlevi — APPROVED** [review]

**Comment by vividroyjeong** [comment]
@dhlevi please review this PR
I couldn't merge with the main branch after the previous review because there were issues in the backend at the time, and the backend issues were recently fixed. This is because I was asked not to merge with main if there was an error under PR validation. 
So the changes since the previous review have been added to this PR, and I apologize for any unintentional inconvenience to your review. As you suggested last time, I wanted to avoid too many review requests at once, but this time it was unintentionally merged with this PR. 

The main changes are listed below:
- Add display and print error message feature in View Error Messages screen
- Re-create client library with the release of the API in version2 and update API integration layer
- Configure to communicate with API

**Review by dhlevi — APPROVED** [review]

**Pull request merged**
